### ISSUE TITLE
Example does not work with remote swagger json file

### ISSUE THREAD

**Issue by mpetyx** [digium/swagger-py#3]
Hello,
I really liked the idea of this project, but I am not yet able to run the example code.

I am trying to execute:

```
import json

from swaggerpy.client import SwaggerClient
from swaggerpy.http_client import SynchronousHttpClient

http_client = SynchronousHttpClient()
http_client.set_basic_auth('swagger.wordnik.com', 'hey', 'peekaboo')

ari = SwaggerClient(
    # "http://localhost:8088/ari/api-docs/resources.json",
    "http://swagger.wordnik.com/#!/pet.json",
    http_client=http_client)
```

but i get this:

```
Traceback (most recent call last):
  File "/path/swaggerToObject.py", line 16, in <module>
    http_client=http_client)
  File "/Library/Python/2.7/site-packages/swaggerpy/client.py", line 178, in __init__
    self.api_docs = loader.load_resource_listing(url_or_resource)
  File "/Library/Python/2.7/site-packages/swaggerpy/swagger_model.py", line 161, in load_resource_listing
    resource_listing = json_load_url(self.http_client, resources_url)
  File "/Library/Python/2.7/site-packages/swaggerpy/swagger_model.py", line 122, in json_load_url
    resp = http_client.request('GET', url)
  File "/Library/Python/2.7/site-packages/swaggerpy/http_client.py", line 178, in request
    return self.session.send(self.session.prepare_request(req))
AttributeError: 'Session' object has no attribute 'prepare_request'

```

Any ideas?
Thank you very much!

**Comment by lwalenl** [comment]
I have the same problem too!
C:\Python34\python.exe D:/strikersoft_git/crowdsoft-test/web-api-tests/api-loadtests/tmp.py
Traceback (most recent call last):
  File "D:/strikersoft_git/crowdsoft-test/web-api-tests/api-loadtests/tmp.py", line 1, in <module>
    from swaggerpy import client
  File "C:\Python34\lib\site-packages\swaggerpy\__init__.py", line 13, in <module>
    from swagger_model import load_file, load_json, load_url, Loader
ImportError: No module named 'swagger_model'

Process finished with exit code 1

**Comment by s-hoviegar** [comment]
I have the same problem. I tried to install swaggerpy with command pip install swaggerpy, but it says it's already installed. These codes are obsolete and out of date there are many problems in them.

**Comment by DIMON1702** [comment]
I got rid of errors when I commented out these 2 lines in `__init__.py`
```
# from swagger_model import load_file, load_json, load_url, Loader
# from processors import SwaggerProcessor, SwaggerError
```
